# Generated by Django 4.1 on 2022-08-23 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_review_movie_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="movie_id",
            new_name="movie",
        ),
    ]
