# Generated by Django 4.1 on 2022-08-23 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_rename_movie_id_review_movie"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="user",
            new_name="critic",
        ),
    ]
